# Generated by Django 5.0.6 on 2024-06-14 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_tiendaonline_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carrito de Compras',
            },
        ),
        migrations.DeleteModel(
            name='admin1',
        ),
        migrations.DeleteModel(
            name='adPedidos',
        ),
        migrations.DeleteModel(
            name='adTienda',
        ),
        migrations.DeleteModel(
            name='adUsuarios',
        ),
        migrations.DeleteModel(
            name='adVentas',
        ),
        migrations.DeleteModel(
            name='detalleCompra',
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
        migrations.DeleteModel(
            name='perfilusuario',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.DeleteModel(
            name='TiendaOnline',
        ),
    ]
