# Generated by Django 5.0.6 on 2024-06-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_cartitem_delete_admin1_delete_adpedidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='camisetas/')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
