# Generated by Django 5.0.6 on 2024-06-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_admin1_adpedidos_adtienda_adusuarios_adventas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='camisetas/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tallas', models.CharField(max_length=100)),
            ],
        ),
    ]
