# Generated by Django 5.0.6 on 2024-06-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_camiseta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
