# Generated by Django 5.0.6 on 2024-06-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_camiseta_id_alter_camiseta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
