# Generated by Django 5.0.6 on 2024-06-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_alter_camiseta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(upload_to='perfilusuario'),
        ),
    ]
